version: "3.2"
services:  
  sapsucker:
    build: .
    container_name: SAPsucker-CLI
    command: python /home/query-builder.py
    env_file: 
        - ./configuration.env
    volumes:
        - ./nwrfcsdk/:/usr/sap/nwrfcsdk/
        - ./:/home/

